### ISSUE TITLE
点击分时闪退com.wk.chart.module.TimeLineChartModule cannot be cast to com.wk.chart.module.CandleChartModule

### ISSUE THREAD

**Issue by hloong** [LLWenke/InteractiveChart#11]
java.lang.ClassCastException: com.wk.chart.module.TimeLineChartModule cannot be cast to com.wk.chart.module.CandleChartModule
        at com.wk.chart.drawing.CursorDrawing.onInit(CursorDrawing.java:25)
        at com.wk.chart.module.base.AbsChartModule.initDrawing(AbsChartModule.java:127)
        at com.wk.chart.render.AbsRender.onViewRectChange(AbsRender.java:343)
        at com.wk.chart.ChartView.onViewChanged(ChartView.java:579)
        at com.wk.demo.activity.ChartActivity.switchModuleType(ChartActivity.java:325)
        at com.wk.demo.activity.ChartActivity.onClick(ChartActivity.java:288)
        at android.view.View.performClick(View.java:4848)
        at android.widget.CompoundButton.performClick(CompoundButton.java:120)
        at android.view.View$PerformClick.run(View.java:20262)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5714)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by hloong** [comment]
已经提交Pull
